---
################################################
## Packages Presence
################################################

homeassistant:
  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'presence'

    ################################################
    ## Sensor
    ################################################

    sensor.klaas_status:
      <<: *customize
      entity_picture: /local/klaas.jpg

    ################################################
    ## Input Select
    ################################################

    input_select.klaas_status_dropdown:
      <<: *customize
      hidden: true

    ################################################
    ## Automation
    ################################################

    automation.markeer_persoon_als_lang_weg:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_net_aangekomen:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_net_vertrokken:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_thuis:
      <<: *customize
      hidden: true

    automation.markeer_persoon_als_weg:
      <<: *customize
      hidden: true

################################################
## Input Select
################################################
input_select:
  # Aanwezigheids optie Klaas
  klaas_status_dropdown:
    name: Klaas
    options:
      - Thuis
      - Net Aangekomen
      - Net Vertrokken
      - Weg
      - Lang Weg

################################################
## Sensor
################################################
sensor:
  - platform: template
    sensors:
      klaas_status:
        value_template: '{{ states.input_select.klaas_status_dropdown.state }}'
        friendly_name: 'Klaas'

################################################
## Automation
################################################
automation:
  # Net Aangekomen
  - alias: '[Presence] - Markeer persoon als net aangekomen'
    description: >-
      Change state of a person to just arrived.

    id: 0e3ca66b-1816-49f5-9f3f-bcb15d7e03c4
    mode: single
    initial_state: true
    trigger:
      # Klaas
      - platform: state
        entity_id: binary_sensor.klaas_at_home
        from: 'off'
        to: 'on'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.klaas_status_dropdown
          option: >
            {% if states.input_select.klaas_status_dropdown.state == 'Net Vertrokken' %}
              Thuis
            {% else %}
              Net Aangekomen
            {% endif %}

  # Thuis
  - alias: '[Presence] - Markeer persoon als thuis'
    description: >-
      Change state of a person to home

    id: 43c1a0d2-c066-4f35-b4a3-7504fb9bdfbb
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.klaas_status_dropdown
        to: 'Net Aangekomen'
        for: "00:15:00"
      - platform: state
        entity_id: input_select.klaas_status_dropdown
        from: 'Net Vertrokken'
        to: 'Net Aangekomen'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.klaas_status_dropdown
          option: Thuis

  # Net Vertrokken
  - alias: '[Presence] - Markeer persoon als net vertrokken'
    description: >-
      Change state of a person to just leaved

    id: 4a5458c2-8eb0-4e38-8967-bf03b5fdcf3c
    mode: single
    initial_state: true
    trigger:
      # Klaas
      - platform: state
        entity_id: binary_sensor.klaas_at_home
        from: 'on'
        to: 'off'
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.klaas_status_dropdown
          option: Net Vertrokken

  # Weg
  - alias: '[Presence] - Markeer persoon als weg'
    description: >-
      Change state of a person to away

    id: fceea58c-1ae9-4c71-9cf4-3466eb28906a
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.klaas_status_dropdown
        to: 'Net Vertrokken'
        for: "00:10:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.klaas_status_dropdown
          option: Weg

  # Lang weg
  - alias: '[Presence] - Markeer persoon als lang weg'
    description: >-
      Change state of a person to long away

    id: 73c2da46-5c02-41dc-812f-4910e2b27dc5
    mode: single
    initial_state: true
    trigger:
      - platform: state
        entity_id: input_select.klaas_status_dropdown
        to: 'Weg'
        for: "24:00:00"
    action:
      - service: input_select.select_option
        data_template:
          entity_id: input_select.klaas_status_dropdown
          option: Lang Weg
