---
################################################
## Packages - System Info
################################################

homeassistant:
  customize_glob:
    weblink.*:
      icon: mdi:web

  customize:
    ################################################
    ## Node Anchors
    ################################################

    package.node_anchors:
      customize: &customize
        package: 'system'

      expose: &expose
        <<: *customize
        haaska_hidden: false
        homebridge_hidden: false

    ################################################
    ## Sensor
    ################################################

    sensor.processor_use:
      <<: *customize
      friendly_name: Processorgebruik

    sensor.memory_use_percent:
      <<: *customize
      friendly_name: Geheugengebruik

    sensor.disk_free:
      <<: *customize
      friendly_name: Beschikbare opslag

    sensor.disk_use_percent:
      <<: *customize
      friendly_name: Gebruikte opslag

    sensor.current_version:
      <<: *customize
      friendly_name: HA geinstalleerde versie

    sensor.python_version:
      <<: *customize
      friendly_name: Python geinstalleerde versie

    sensor.last_boot:
      <<: *customize
      friendly_name: Laatste (re)boot Intel NUC

    sensor.myip:
      <<: *customize
      friendly_name: Publiek IP-adres
      icon: mdi:network

    sensor.local_ip:
      <<: *customize
      friendly_name: Intern IP-adres
      icon: mdi:network

################################################
## Binary Sensor
################################################

binary_sensor:
  - platform: template
    sensors:
      cpu_high:
        value_template: '{{ states.sensor.processor_use.state | float > 80 }}'
        friendly_name: 'CPU hoog'
  - platform: template
    sensors:
      cpu_hot:
        value_template: '{{ states.sensor.cpu_temperature.state | float > 65 }}'
        friendly_name: 'CPU heet'

################################################
## Sensor
################################################

sensor:
  - platform: systemmonitor
    resources:
      - type: memory_use_percent
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: disk_free
        arg: /
      - type: last_boot
      - type: swap_use_percent

##### Latest installed python3 version
command_line:
  - sensor:
      name: Python Version
      command: python3 --version
      scan_interval: 86400

################################################
## Input boolean
################################################

input_boolean:
  maintenance_mode:
    name: Onderhouds Mode
    icon: mdi:auto-fix

################################################
## Alert
################################################

alert:
  # cpu_high:
  #   name: Gebruik CPU is hoog
  #   entity_id: binary_sensor.cpu_high
  #   state: 'on'
  #   repeat: 5   # minutes
  #   can_acknowledge: true
  #   skip_first: false
  #   notifiers:
  #     - telegram_klaas

  # cpu_hot:
  #   name: Temperatuur CPU is hoog
  #   entity_id: binary_sensor.cpu_hot
  #   state: 'on'
  #   repeat: 120   # minutes
  #   can_acknowledge: true
  #   skip_first: false
  #   notifiers:
  #     - telegram_klaas

  maintenance_mode_alert:
    name: Onderhouds Mode staat al aan voor een lange tijd
    done_message: Maintenance Mode de-activated
    entity_id: input_boolean.maintenance_mode
    repeat:
      - 60
    skip_first: true
    notifiers:
      - telegram_klaas
