---
homeassistant:
  # Customization #
  customize: !include_dir_merge_named customizations/entities
  # Lets me custimize all entities in a domain
  customize_domain: !include_dir_merge_named customizations/domains
  # Packages #
  packages: !include_dir_named integrations
  # Whitelist #
  allowlist_external_dirs:
    - "/config/"
  # Authentication #
  auth_providers:
    - type: homeassistant

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

python_script:
