---
# This is actually just a bootstrap for my Lovelace configuration.

# It loads all resources for Lovelace dynamically from subfolders
# inside the `lovelace/resources` directory.
#
# Views are actually include one by one, this to guarentee the order of
# the tabs of the view in the UI.
#
title: Student Home
views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/floorplan.yaml
  - !include lovelace/views/security.yaml
  - !include lovelace/views/3d_printer.yaml
  - !include lovelace/views/temperature.yaml
  - !include lovelace/views/media_player.yaml
  - !include lovelace/views/all_automations.yaml
  - !include lovelace/views/system.yaml
