---
- alias: "[Voice] - Evening lights"
  description: Activating the evening lights scene

  id: 5cb83534-4136-4c54-a767-43c37fe069f5
  mode: single

  triggers:
    - alias: Trigger sentence
      trigger: conversation
      command:
        - Het is avond
        - Mag het licht aan
  conditions: []
  actions:
    - action: scene.turn_on
      data:
        transition: 2
      target:
        entity_id: scene.evening
    - set_conversation_response: Begrepen, ik zal de lampen als sfeerverlichting aanzetten.
