# Services.yaml for google_home integration

reboot_device:
  target:
    entity:
      domain: sensor
      integration: google_home

delete_alarm:
  fields:
    entity_id:
      example: "sensor.kitchen_alarms"
      required: true
      selector:
        entity:
          domain: sensor
          integration: google_home
    skip_refresh:
      example: true
      default: false
      required: false
      selector:
        boolean:
    alarm_id:
      example: "alarm/6ed06a56-8a58-c6e3-a7d4-03f92c9d8a51"
      required: true
      selector:
        text:

delete_timer:
  fields:
    entity_id:
      example: "sensor.kitchen_timers"
      required: true
      selector:
        entity:
          domain: sensor
          integration: google_home
    skip_refresh:
      example: true
      default: false
      required: false
      selector:
        boolean:
    timer_id:
      example: "timer/6ed06a56-8a58-c6e3-a7d4-03f92c9d8a51"
      required: true
      selector:
        text:

refresh_devices:
