---
# Automate the bathroom light
# The lights go on by opening the door and goes off every 15 minutes when the door is closed
# Also the lights will be dimmed in the night
#
- alias: '[Light] - Turn ON bathroom light'
  description: >-
    Turn the light on when I open a door or if there is occupancy

  id: 2498664e-7b8d-4de5-9613-25435b183274
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_door_contact, binary_sensor.badkamer_presence_occupancy
      to: 'on'
      from: 'off'
  action:
    - service: light.turn_on
      target:
        entity_id: light.bathroom
      data_template:
        color_temp: 380
        brightness_pct: >
          {% if is_state ('binary_sensor.night' , 'on') %} 15
          {% else %} 70
          {% endif %}

- alias: '[Light] - Turn OFF bathroom light'
  description: >-
    Turn the light off when there is no motion for 6 minutes

  id: 40f79c91-8483-4ef7-b6d5-4025ad306276
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.badkamer_presence_occupancy
      to: 'off'
  condition:
    # Keep the light on when you take a shower
    - condition: numeric_state
      entity_id: sensor.bathroom_sensor_humidity
      below: 75
  action:
    - service: light.turn_off
      target:
        entity_id: light.bathroom

- alias: '[Light] - Shower warning - 5 min'
  description: >-
    Show me a green color warning when showring for 5 min

  id: f793694b-3cb0-41a8-99b0-53e89cfe0b17
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.shower
      to: 'on'
      for:
        minutes: 5
  condition:
    # The bathroom light should be ON
    - condition: state
      entity_id: light.bathroom
      state: 'on'
  action:
    - service: scene.create
      data:
        scene_id: bathroom_before
        snapshot_entities:
          - light.bathroom
    - service: light.turn_on
      target:
        entity_id: light.bathroom
      data:
        transition: 5
        rgb_color: [109, 255, 108]
    - delay: 00:00:10
    - service: scene.turn_on
      target:
        entity_id: scene.bathroom_before

- alias: '[Light] - Shower warning - 10 min'
  description: >-
    Show me a red color warning when showring to loooooooong

  id: 6ae1e947-7ca9-4d81-9ff0-640759f353f8
  mode: single

  trigger:
    - platform: state
      entity_id: binary_sensor.shower
      to: 'on'
      for:
        minutes: 10
  condition:
    # The bathroom light should be ON
    - condition: state
      entity_id: light.bathroom
      state: 'on'
  action:
    - service: scene.create
      data:
        scene_id: bathroom_before
        snapshot_entities:
          - light.bathroom
    - service: light.turn_on
      target:
        entity_id: light.bathroom
      data:
        transition: 5
        rgb_color: [255, 75, 75]
    - delay: 00:00:10
    - service: scene.turn_on
      target:
        entity_id: scene.bathroom_before
