---
- alias: '[House] - Forgot the lights'
  description: >-
    Automation for when a light is still ON in my house when I leave

  id: fb712601-6f02-4908-9ec1-4213ca66a99b
  mode: single

  trigger:
    # Outside home zone
    - platform: zone
      entity_id: person.klaas_schoute
      zone: zone.home
      event: leave
  condition:
    condition: or
    conditions:
      # If a light is still on
      - condition: state
        entity_id: light.livingroom
        state: 'on'
      - condition: state
        entity_id: light.kitchen
        state: 'on'
      - condition: state
        entity_id: light.hall
        state: 'on'
      - condition: state
        entity_id: light.bathroom
        state: 'on'
      - condition: state
        entity_id: light.bureau
        state: 'on'
  action:
    # HA Android notification
    - service: notify.mobile_app_klaas_samsung_s24_plus
      data:
        title: 'Lampen vergeten!'
        message: >
          Je bent vertrokken, maar de lampen staan nog aan.
        data:
          actions:
            - action: turn_light_off
              title: Zet lampen UIT

- alias: '[House] - Light turns on in empty house'
  description: >-
    Notify when a light was turned on but nobody is home

  id: 20faccbc-348c-4520-abdb-9d7d9f6827ea
  mode: single

  trigger:
    - platform: state
      entity_id:
        - light.bathroom
        - light.hall
        - light.kitchen
        - light.livingroom
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: device_tracker.klaas_samsung_s24_plus
      state: 'not_home'
  action:
    - service: notify.mobile_app_klaas_samsung_s24_plus
      data:
        title: 'Lamp is aan gegaan!'
        message: >
          Een lamp uit de groep {{ trigger.to_state.attributes.friendly_name }} is aan gegaan.
        data:
          actions:
            - action: turn_light_off
              title: Zet lampen UIT

- alias: '[Light] - Turn all light off'
  description: >-
    Turn all light of when start action from notification

  id: ca887d6b-7d28-4150-b821-4002f996a0f5
  mode: single

  trigger:
    # Actionable notification event trigger
    - platform: event
      event_type: mobile_app_notification_action
      event_data:
        action: turn_light_off
  action:
    # Turn all lights off
    - service: script.turn_on
      target:
        entity_id: script.all_lights_off
