---
- alias: '[Light] - Kitchen automated'
  description: >-
    Turn the lights on if LUX value is low or on if high

  id: b7776a4c-39ec-4c97-8234-98cc2f7c3cf3
  mode: single
  trigger:
    - platform: numeric_state
      entity_id:
        - sensor.kitchen_light_sensor_illuminance
      below: input_number.lux_value_kitchen_low
    - platform: numeric_state
      entity_id:
        - sensor.kitchen_light_sensor_illuminance
      above: input_number.lux_value_kitchen_high
  condition:
    # Check if Automated lights mode is enabled
    - condition: state
      entity_id: input_boolean.lights_automated
      state: 'on'
    # Check if I'm home :)
    - condition: state
      entity_id: sensor.klaas_status
      state: 'Thuis'
  action:
    - choose:
        # ON
        - conditions:
            - condition: template
              value_template: "{{ ((trigger.to_state.state)|float) <= (states('input_number.lux_value_kitchen_low')|float) }}"
            # Check if light are off
            - condition: state
              entity_id: light.hall
              state: 'off'
            - condition: state
              entity_id: light.z2m_kitchen
              state: 'off'
          sequence:
            - service: logbook.log
              data:
                name: Hal & Keuken
                message: "- Lampen worden automatisch ingeschakeld"
                entity_id: light.z2m_kitchen
            - service: light.turn_on
              target:
                entity_id:
                  - light.hall
                  - light.z2m_kitchen
              data:
                brightness_pct: "{{ states('input_number.brightness_dimmed') | round }}"
        # OFF
        - conditions:
            - condition: template
              value_template: "{{ ((trigger.to_state.state)|float) >= (states('input_number.lux_value_kitchen_high')|float) }}"
            # Check if light are on
            - condition: state
              entity_id: light.hall
              state: 'on'
            - condition: state
              entity_id: light.z2m_kitchen
              state: 'on'
          sequence:
            - service: logbook.log
              data:
                name: Hal & Keuken
                message: "- Lampen worden automatisch uitgeschakeld"
                entity_id: light.z2m_kitchen
            - service: light.turn_off
              target:
                entity_id:
                  - light.hall
                  - light.z2m_kitchen
