---
- alias: '[House] - Forgot the air conditioning'
  description: >-
    Automation for when the airco is still ON in my house when I leave

  id: f6247cce-8ce4-4498-b759-8eff5e63480a
  mode: single

  trigger:
    # Outside home zone
    - platform: zone
      entity_id: person.klaas_schoute
      zone: zone.home
      event: leave
  condition:
    - condition: state
      entity_id: switch.airco
      state: 'on'
  action:
    # HA Android notification
    - service: notify.mobile_app_klaas_samsung_s22_plus
      data:
        title: 'Airco vergeten!'
        message: >
          Je bent vertrokken, maar de Airco staat nog aan.
