---
- alias: '[People] - Notify when phone is fully charged'
  description: >-
    Give me a TTS notification when my phone is full charged
    and only if I am home and it is before midnight

  id: 1bb2fb11-efdc-41c4-823a-e39f9b4902d6
  mode: single

  trigger:
    - platform: numeric_state
      entity_id: sensor.klaas_samsung_s22_plus_battery_level
      above: 99
      for: '00:03:00'
  condition:
    # And I also have to be home :)
    - condition: state
      entity_id: sensor.klaas_status
      state: 'Thuis'
    - condition: state
      entity_id: binary_sensor.night
      state: 'off'
  action:
    - service: notify.woonkamer
      data:
        message: 'Je telefoon is 100% opgeladen'
