---
- alias: '[System] - Notify on Home Assistant update'
  description: >-
    Send a notification when there is a new update
  id: 536bc66c-c91d-436f-afe1-174dbc424862
  mode: single

  use_blueprint:
    path: fortepc/update-notif-for-android.yaml
    input:
      clickAction: https://my.home-assistant.io/redirect/supervisor/
      delay: 0
      notify_device: 6a16c24c60507cdb3712c249d13133c3
      notification_title: Tijd om te upgraden!
      group: Updates
      notification_message: 'Er is een nieuwe versie voor Home Assistant beschikbaar,
        versie: {{ newest_version }}'
