---
blueprint:
  name: Z2M - Aqara D1 (1 way) remote for cover
  description: |
    Control cover with an Aqara D1 (1 way) remote (WXKG06LM).

    - single press to open cover
    - double press to close cover
    - long press to stop the cover from moving
  domain: automation
  input:
    remote:
      name: Aqara D1 remote action
      description: >
        This must be an "action" event entity provided by zigbee2mqtt. For example "event.living_dimmer_action"
      selector:
        entity:
          integration: mqtt
          domain: event
    cover:
      name: Cover
      description: The cover to control
      selector:
        target:
          entity:
            domain: cover

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input remote
    not_from:
      - unavailable
      - unknown

action:
  - variables:
      event: "{{ trigger.to_state.attributes.event_type | default('unknown', true) }}"

  - choose:
      # Curtain closing
      - conditions: "{{ event == 'double' }}"
        sequence:
          - service: cover.open_cover
            target: !input 'cover'
            data: {}
      # Curtain open
      - conditions: "{{ event == 'single' }}"
        sequence:
          - service: cover.close_cover
            target: !input 'cover'
            data: {}
      # Stop curtain
      - conditions: "{{ event == 'hold' }}"
        sequence:
          - service: cover.stop_cover
            target: !input 'cover'
            data: {}
