---
blueprint:
  name: Z2M - Aqara Opple (6 way) remote for lights
  description: |
    Control 3 lights with an Aqara Opple switch 3 bands (WXCJKG13LM).

    Each band controls one light/group.
    - single press to turn ON or OFF the lights
    - long press to increase or decrease the brightness smoothly until released
    - double press to adjust the brightness to 100% or 10%

    In addition, you also have the choice to determine a forced brightness for when you turn on the lights.
  domain: automation
  input:
    remote:
      name: Opple remote
      description: >
        This must be an "action" event entity provided by zigbee2mqtt. For example "event.living_dimmer_action"
      selector:
        entity:
          integration: mqtt
          domain: event
    light_1:
      name: Light(s)
      description: The first light(s group) to control
      selector:
        target:
          entity:
            domain: light
    light_2:
      name: Light(s)
      description: The second light(s group) to control
      selector:
        target:
          entity:
            domain: light
    light_3:
      name: Light(s)
      description: The third light(s group) to control
      selector:
        target:
          entity:
            domain: light
    force_brightness:
      name: Force turn on brightness
      description: >
        Force the brightness to the set level below, when the "on" button on
        the remote is pushed and lights turn on.
      default: false
      selector:
        boolean:
    brightness:
      name: Brightness
      description: Brightness of the light(s) when turning on
      default: 50
      selector:
        number:
          min: 0
          max: 100
          mode: slider
          step: 1
          unit_of_measurement: "%"

mode: restart
max_exceeded: silent

variables:
  force_brightness: !input force_brightness

trigger:
  - platform: state
    entity_id: !input remote
    not_from:
      - unavailable
      - unknown

action:
  - variables:
      event: "{{ trigger.to_state.attributes.event_type | default('unknown', true) }}"
      button: "{{ trigger.to_state.attributes.button | default('unknown') }}"

  - choose:
      # ---------------------------- TURN ON OR OFF ---------------------------- #
      - conditions: "{{ event == 'button_1_single' }}"
        sequence:
          - choose:
              - conditions: "{{ force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target: !input 'light_1'
                    data:
                      transition: 1
                      brightness_pct: !input brightness
            default:
              - service: light.turn_on
                target: !input 'light_1'
                data: {}
      - conditions: "{{ event == 'button_2_single' }}"
        sequence:
          - service: light.turn_off
            data: {}
            target: !input 'light_1'
      - conditions: "{{ event == 'button_3_single' }}"
        sequence:
          - choose:
              - conditions: "{{ force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target: !input 'light_2'
                    data:
                      transition: 1
                      brightness_pct: !input brightness
            default:
              - service: light.turn_on
                target: !input 'light_2'
                data: {}
      - conditions: "{{ event == 'button_4_single' }}"
        sequence:
          - service: light.turn_off
            data: {}
            target: !input 'light_2'
      - conditions: "{{ event == 'button_5_single' }}"
        sequence:
          - choose:
              - conditions: "{{ force_brightness }}"
                sequence:
                  - service: light.turn_on
                    target: !input 'light_3'
                    data:
                      transition: 1
                      brightness_pct: !input brightness
            default:
              - service: light.turn_on
                target: !input 'light_3'
                data: {}
      - conditions: "{{ event == 'button_6_single' }}"
        sequence:
          - service: light.turn_off
            data: {}
            target: !input 'light_3'
      # ---------------------------- INCREASE OR DECREASE BRIGHTNESS ---------------------------- #
      - conditions:
          - condition: template
            value_template: "{{ event == 'hold' and button == 'button_1' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: button_1_release
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                  target: !input 'light_1'
                - delay: 0.2
      - conditions:
          - condition: template
            value_template: "{{ event == 'hold' and button == 'button_2' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: button_2_release
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                  target: !input 'light_1'
                - delay: 0.2
      - conditions:
          - condition: template
            value_template: "{{ event == 'hold' and button == 'button_3' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: button_3_release
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                  target: !input 'light_2'
                - delay: 0.2
      - conditions:
          - condition: template
            value_template: "{{ event == 'hold' and button == 'button_4' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: button_4_release
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                  target: !input 'light_2'
                - delay: 0.2
      - conditions:
          - condition: template
            value_template: "{{ event == 'hold' and button == 'button_5' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: button_5_release
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: 10
                    transition: 0.5
                  target: !input 'light_3'
                - delay: 0.2
      - conditions:
          - condition: template
            value_template: "{{ event == 'hold' and button == 'button_6' }}"
        sequence:
          - repeat:
              until:
                - condition: state
                  entity_id: !input remote
                  state: button_6_release
              sequence:
                - service: light.turn_on
                  data:
                    brightness_step_pct: -10
                    transition: 0.5
                  target: !input 'light_3'
                - delay: 0.2
      # ---------------------------- MAX OR MIN BRIGHTNESS ---------------------------- #
      # ---------- MAX ---------- #
      - conditions: "{{ event == 'button_1_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
              transition: 0.5
            target: !input 'light_1'
      - conditions: "{{ event == 'button_3_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
              transition: 0.5
            target: !input 'light_2'
      - conditions: "{{ event == 'button_5_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
              transition: 0.5
            target: !input 'light_3'
      # ---------- MIN ---------- #
      - conditions: "{{ event == 'button_2_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 10
              transition: 0.5
            target: !input 'light_1'
      - conditions: "{{ event == 'button_4_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 10
              transition: 0.5
            target: !input 'light_2'
      - conditions: "{{ event == 'button_6_double' }}"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 10
              transition: 0.5
            target: !input 'light_3'
