---
# Automation that handle IFTTT requests
#
- alias: '[System] - IFTTT Handling'
  initial_state: true
  trigger:
    - platform: event
      event_type: ifttt_webhook_received
      event_data:
        action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
      channel: '{{ trigger.event.data.channel }}'
