---
- alias: '[House] - Wake up ritual'
  description: >-
    Start wakeup sequence

  id: 6db6c97d-fe7d-4217-a8f1-0dd3c01804b0
  mode: single

  trigger:
    # Trigger is moment that current time is 10 minutes before alarm
    # Samsung app Alarm
    - platform: state
      entity_id: binary_sensor.mobile_wakeup_alarm
      to: 'on'
    # Manual Alarm
    - platform: template
      value_template: >
        {{ is_state('binary_sensor.manual_wakeup_alarm', 'on') and
        states('sensor.klaas_samsung_s20_plus_volgende_alarm') in ('none', 'unavailable', 'unknown') }}
  condition:
    condition: and
    conditions:
      # Condition is that I went to bed
      - condition: state
        entity_id: input_boolean.go_to_sleep
        state: 'on'
      # And I also have to be home :)
      - condition: state
        entity_id: sensor.klaas_status
        state: 'Thuis'
      # check if I have setup an alarm
      - condition: state
        entity_id: input_boolean.wakeup_with_alarm
        state: 'on'
  action:
    # Start wake up script ritual
    - service: script.wake_up
      data_template:
        entity_id: "{{ trigger.entity_id }}"
